Market guide scrolling issue #1583
blockchainprojects/bitshares-ui pull request #26
Opened 2018-10-19 18:09 UTC by VerevkinAlexander

Added method that scrolls central element of Exchange page to highlited.

2018-10-22 11:40 UTC, VerevkinAlexander commented
@sschiessl-bcp Please review it , when you have time.

2018-10-23 12:45 UTC, sschiessl-bcp commented
This solution only works for this one component, and also only if there is no help element in the top area of the exchange (because then you would need to scroll up). 

Did you see the comments and hints in the original issue?

2018-10-24 15:16 UTC, VerevkinAlexander commented
You mentioned on comments. Did you mean next one? :
-"According to index.js, it works with auto positioning, https://introjs.com/example/auto-position/index.html. Though, I believe that Perfect scrollbar has something to with it not working."
-"Might be enough to update intro.js"

2018-10-25 08:29 UTC, sschiessl-bcp commented
> You mentioned on comments. Did you mean next one? :
> -"According to index.js, it works with auto positioning, https://introjs.com/example/auto-position/index.html. Though, I believe that Perfect scrollbar has something to with it not working."
> -"Might be enough to update intro.js"

Yes, those two I am referring to!

2018-10-25 10:20 UTC, VerevkinAlexander commented
I tried them but it did not fix our issue. Sorry, that I did not mention you about it.

2018-10-25 10:38 UTC, sschiessl-bcp commented
I see. Any fix must be working for any help setup, not just one specific. 

Let's postpone this for now, possible that intro.js needs a fix

2018-11-06 09:54 UTC, sschiessl-bcp requested changes
The rendering is still broken 

![image](https://user-images.githubusercontent.com/33128181/48056504-3ab26c00-e1b2-11e8-98db-67ca6fca2c27.png)

![image](https://user-images.githubusercontent.com/33128181/48056474-2ec6aa00-e1b2-11e8-94fd-0c789f5216c8.png)

2018-11-06 09:54 UTC, sschiessl-bcp commented on app/components/Layout/Footer.jsx
> +        const chartDiv = document.getElementsByClassName(
This way of fixing the issue would require a custom solution for *every* panel that uses intro.js.

2018-11-06 09:54 UTC, sschiessl-bcp commented
Any solution must be a generic one, and not tailored to a specific panel like the exchange. 

If there is no suitable fix atm, so be it.

2018-11-06 10:29 UTC, VerevkinAlexander commented
intro.js scrolling works only for blocks that directly contains in a scrollable block if intro.js hint block is placed in the not scrollable block it needs some additional method for detecting and scrolling main scrollable block. So its need block position calculating for each panel. Also if browser window height is smaller than panel height you will see blank gray block.

2019-03-05 11:00 UTC, closed without merging